import { doc } from "../../../../../shared/interface/doc";


export const docData: doc[] = [
    { 
        doc_no:'0816/2563',
        doc_head:'ขออนุญาติให้นักศึกษาเข้าร่วมกิจกรรม',
        date_write:'29-08-2023',
        time_write:'15.30',
        date_active:'30-08-2023',
        date_in:'30-08-2023',
        doc_type_name:'เอกสารโครงการต่าง ๆ',
        doc_type_id:1,
        seen:false,
        doc_state_name:'ดำเนินการ',
        doc_state_id:1,
        term:2,
        year:2563,
        teacher_id:[1,2,3],
        check:false
    },
    { 
        doc_no:'ศธ 1424/2563',
        doc_head:'แจ้งหยุดเรียนกรณีพิเศษ',
        date_write:'28-03-2023',
        time_write:'11.09',
        date_active:'10-08-2023',
        date_in:'29-03-2023',
        doc_type_name:'เอกสารบุคคล',
        doc_type_id:2,
        seen:false,
        doc_state_name:'ดำเนินการ',
        doc_state_id:1,
        term:2,
        year:2563,
        teacher_id:[1,2,3],
        check:false
    },
    { 
        doc_no:'598/2561',
        doc_head:'ขอเชิญประชุมโครงการพัฒนาคุณภาพการศึกษา',
        date_write:'11-03-2023',
        time_write:'13.45',
        date_active:'15-04-2023',
        date_in:'14-04-2023',
        doc_type_name:'เอกสารทั่วไป',
        doc_type_id:3,
        seen:false,
        doc_state_name:'หมดอายุ',
        doc_state_id:2,
        term:2,
        year:2561,
        teacher_id:[1,2,3],
        check:false
    },
    { 
        doc_no:'ศธ 0516/2564',
        doc_head:'ขอความอนุเคราะห์จัดส่งบุคลากรเข้าอบรม',
        date_write:'01-07-2021',
        time_write:'12.59',
        date_active:'29-08-2021',
        date_in:'02-07-2021',
        doc_type_name:'เอกสารถึงหัวหน้าสาขา',
        doc_type_id:4,
        seen:true,
        doc_state_name:'หมดอายุ',
        doc_state_id:2,
        term:1,
        year:2564,
        teacher_id:[1,2,3],
        check:false
    },
    { 
        doc_no:'ศธ 0502/2566',
        doc_head:'ขอความอนุเคราะห์จัดส่งบุคลากรเข้าอบรม',
        date_write:'01-06-2024',
        time_write:'13.05',
        date_active:'02-06-2024',
        date_in:'02-07-2024',
        doc_type_name:'เอกสารถึงหัวหน้าสาขา',
        doc_type_id:4,
        seen:false,
        doc_state_name:'ดำเนินการ',
        doc_state_id:1,
        term:2,
        year:2566,
        teacher_id:[1,2,3],
        check:false
    },
    { 
        doc_no:'ศธ 6726/2566',
        doc_head:'สำเนาหนังสือรายงาน',
        date_write:'08-07-2023',
        time_write:'09.09',
        date_active:'09-07-2023',
        date_in:'08-07-2023',
        doc_type_name:'เอกสารถึงรองฝ่ายบริหาร',
        doc_type_id:4,
        seen:false,
        doc_state_name:'ดำเนินการ',
        doc_state_id:1,
        term:2,
        year:2566,
        teacher_id:[1,2,3],
        check:false
    },
    
]